### ISSUE TITLE
Add more rolls or implement Zork-style game play

### ISSUE THREAD

**Issue by brando56894** [brando56894/dungeon-quest#6]
Have to look into both, Zork-style would probably make it less repetitive.

**Comment by ghost** [comment]
To better implement Zork style game play, you could make an area of rooms into an array. For Example:
area = [Room1, Room2, Room3,
            Room4, Room5, Room6,
            Room7, Room8, Room9]

In this 3x3 area:
north = area[currentRoom - 3]
south = area[currentRoom + 3]
east = area[currentRoom + 1]
west = area[currentRoom - 1]

To combine directions into something like northeast, no extra calculations are needed, just go north then east, so for each area, just four directions need to be calculated

This might make building a map easier and more organized
